-- ─────────────────────────────────────────────────────────────────────────────
-- Zaujain Database Schema — Part 3 of 6
-- Tables: activation_keys, experiences, experience_members
--
-- Run order: Part 1 → 2 → 3 → 4 → 5 → 6
-- Depends on: Part 1 (enums, handle_updated_at), Part 2 (users, themes)
-- ─────────────────────────────────────────────────────────────────────────────


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: activation_keys
-- Each purchased experience is unlocked with a unique key.
-- Keys are generated by admin and redeemed exactly once by a user.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.activation_keys (
  id            uuid primary key default uuid_generate_v4(),
  key           text not null unique,
  status        activation_key_status not null default 'active',
  product_type  product_type not null default 'digital_gift',
  created_by    uuid not null references public.users(id),
  redeemed_by   uuid references public.users(id),
  redeemed_at   timestamptz,
  expires_at    timestamptz,
  created_at    timestamptz not null default now(),

  -- Enforce that redeemed_by and redeemed_at are always set together
  constraint redeemed_consistency check (
    (redeemed_by is null and redeemed_at is null) or
    (redeemed_by is not null and redeemed_at is not null)
  )
);

create index idx_activation_keys_key on public.activation_keys(key);
create index idx_activation_keys_status on public.activation_keys(status);
create index idx_activation_keys_redeemed_by on public.activation_keys(redeemed_by);

-- RLS
alter table public.activation_keys enable row level security;

create policy "Users can view their own redeemed keys"
  on public.activation_keys for select
  using (auth.uid() = redeemed_by);

create policy "Users can redeem active keys"
  on public.activation_keys for update
  using (status = 'active')
  with check (auth.uid() = redeemed_by);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: experiences
-- The core entity — a digital gift, time capsule, or future experience type.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.experiences (
  id                  uuid primary key default uuid_generate_v4(),
  activation_key_id   uuid not null references public.activation_keys(id),
  owner_id            uuid not null references public.users(id) on delete cascade,
  experience_type     experience_type not null default 'digital_gift',
  title               text not null,
  slug                text not null unique,
  theme_id            uuid references public.themes(id),
  cover_image         text,
  background_music    text,
  welcome_message     text,
  is_private          boolean not null default true,
  status              experience_status not null default 'draft',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint title_length check (char_length(title) between 2 and 80),
  constraint slug_length check (char_length(slug) between 3 and 60),
  constraint slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint welcome_message_length check (char_length(welcome_message) <= 500)
);

create trigger experiences_updated_at
  before update on public.experiences
  for each row execute function handle_updated_at();

create index idx_experiences_owner_id on public.experiences(owner_id);
create index idx_experiences_slug on public.experiences(slug);
create index idx_experiences_status on public.experiences(status);
create index idx_experiences_type on public.experiences(experience_type);

-- RLS
alter table public.experiences enable row level security;

create policy "Owners can manage their experiences"
  on public.experiences for all
  using (auth.uid() = owner_id);

create policy "Members can view shared experiences"
  on public.experiences for select
  using (
    exists (
      select 1 from public.experience_members
      where experience_id = experiences.id
        and user_id = auth.uid()
    )
  );

create policy "Anyone can view published public experiences"
  on public.experiences for select
  using (status = 'published' and is_private = false);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: experience_members
-- Controls which users can access a given experience and in what role.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.experience_members (
  id              uuid primary key default uuid_generate_v4(),
  experience_id   uuid not null references public.experiences(id) on delete cascade,
  user_id         uuid not null references public.users(id) on delete cascade,
  role            experience_member_role not null default 'recipient',
  joined_at       timestamptz not null default now(),

  unique (experience_id, user_id)
);

create index idx_experience_members_experience_id on public.experience_members(experience_id);
create index idx_experience_members_user_id on public.experience_members(user_id);

-- RLS
alter table public.experience_members enable row level security;

create policy "Owners can manage members"
  on public.experience_members for all
  using (
    exists (
      select 1 from public.experiences
      where id = experience_id
        and owner_id = auth.uid()
    )
  );

create policy "Members can view their own membership"
  on public.experience_members for select
  using (auth.uid() = user_id);
