-- Migration: 0005_tables_experiences
-- Description: Create activation_keys, experiences, and experience_members tables
--
-- Dependency order:
--   activation_keys   → users
--   experiences       → users, activation_keys, themes
--   experience_members → users, experiences

-- ── Table: activation_keys ────────────────────────────────────────────────────
-- Each purchased experience is unlocked with a unique, single-use key.
-- Generated by admin; redeemed by users via redeem_activation_key() function.

create table public.activation_keys (
  id            uuid                  primary key default uuid_generate_v4(),
  key           text                  not null unique,
  status        public.activation_key_status not null default 'active',
  product_type  public.product_type   not null default 'digital_gift',
  created_by    uuid                  not null references public.users(id),
  redeemed_by   uuid                  references public.users(id),
  redeemed_at   timestamptz,
  expires_at    timestamptz,
  created_at    timestamptz           not null default now(),

  -- redeemed_by and redeemed_at must be set together or not at all
  constraint activation_keys_redeemed_consistency check (
    (redeemed_by is null and redeemed_at is null) or
    (redeemed_by is not null and redeemed_at is not null)
  )
);

alter table public.activation_keys enable row level security;

create policy "activation_keys_select_own"
  on public.activation_keys for select
  using (auth.uid() = redeemed_by);

create policy "activation_keys_update_redeem"
  on public.activation_keys for update
  using (status = 'active')
  with check (auth.uid() = redeemed_by);


-- ── Table: experiences ────────────────────────────────────────────────────────
-- The central entity — a digital gift, time capsule, or future experience type.
-- Private by default; accessed via personalized slug URL.

create table public.experiences (
  id                  uuid                    primary key default uuid_generate_v4(),
  activation_key_id   uuid                    not null references public.activation_keys(id),
  owner_id            uuid                    not null references public.users(id) on delete cascade,
  experience_type     public.experience_type  not null default 'digital_gift',
  title               text                    not null,
  slug                text                    not null unique,
  theme_id            uuid                    references public.themes(id),
  cover_image         text,
  background_music    text,
  welcome_message     text,
  is_private          boolean                 not null default true,
  status              public.experience_status not null default 'draft',
  created_at          timestamptz             not null default now(),
  updated_at          timestamptz             not null default now(),

  constraint experiences_title_length          check (char_length(title) between 2 and 80),
  constraint experiences_slug_length           check (char_length(slug) between 3 and 60),
  constraint experiences_slug_format           check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint experiences_welcome_msg_length    check (char_length(welcome_message) <= 500)
);

create trigger experiences_updated_at
  before update on public.experiences
  for each row execute function public.handle_updated_at();

alter table public.experiences enable row level security;

create policy "experiences_all_owner"
  on public.experiences for all
  using (auth.uid() = owner_id);

create policy "experiences_select_member"
  on public.experiences for select
  using (
    exists (
      select 1 from public.experience_members
      where experience_id = experiences.id
        and user_id = auth.uid()
    )
  );

create policy "experiences_select_public"
  on public.experiences for select
  using (status = 'published' and is_private = false);


-- ── Table: experience_members ─────────────────────────────────────────────────
-- Controls which users can access a given experience and in what role.
-- Owners manage membership; recipients/viewers can read their own row.

create table public.experience_members (
  id              uuid                         primary key default uuid_generate_v4(),
  experience_id   uuid                         not null references public.experiences(id) on delete cascade,
  user_id         uuid                         not null references public.users(id) on delete cascade,
  role            public.experience_member_role not null default 'recipient',
  joined_at       timestamptz                  not null default now(),

  unique (experience_id, user_id)
);

alter table public.experience_members enable row level security;

create policy "experience_members_all_owner"
  on public.experience_members for all
  using (
    exists (
      select 1 from public.experiences
      where id = experience_id
        and owner_id = auth.uid()
    )
  );

create policy "experience_members_select_self"
  on public.experience_members for select
  using (auth.uid() = user_id);
